export { default as sNews } from './news'
export { default as sLessons } from './lessons'
export { default as sTeachers } from './teachers'
export { default as sVideo } from './video'
export { default as sHunters } from './hunters'
export { default as sJobs } from './jobs'
export { default as sTalents } from './talents'
export { default as sLinks } from './links'